### PR TITLE
fix: "invisibility bug" on AE

### PR DESCRIPTION
**Pull request by DaymareOn**

### CODE REVIEW

**Review by alandtse — APPROVED** [review]
I mean it fixes it, but there's something wrong with the function GetCurrentHeadPartsByType. Is that built in or did we define it?

**Comment by alandtse** [comment]
Oh. It's probably the fact you need to convert node indexes then for head parts.

**Comment by DaymareOn** [comment]
I know nothing about this.
Does that mean that my fix isn't good/enough?

**Comment by alandtse** [comment]
If it works it works. I'm guessing whoever wrote the codedidn't realize that HeadPartByType isn't an iterator but based on biped slot probably.

**Pull request merged**
