### PR TITLE
feat: add wind effect physics

### PR DESCRIPTION
**Pull request by alandtse**
See commits for individual changes. Please note I do not have the AE address and that will need to be added.

### CODE REVIEW

**Comment by DaymareOn** [comment]
Very nice feature :)

I will add numbered comments continuously while reading the code.

1) In WeatherManager.cpp, the dot and Dot functions are identical. I understand you might want to distinguish between points and vectors arguments, but I'm not sure it's a reason enough. Same for cross and crossProduct. dot and cross are implemented elsewhere in the code too. I guess it would be better to have a single implementation, especially as it's inlined.

**Comment by DaymareOn** [comment]
2. In WeatherManager.cpp, there might be some possible micro-optimizations by avoiding the sqrtf and division calls. To see later if it's interesting by profiling.

**Comment by DaymareOn** [comment]
3. Would it be possible to build the list of interior worlds dynamically depending on the installed mods?

**Comment by DaymareOn** [comment]
4. In the configs.xml file, could you please make explicit what is the default value in the code, ie if the value is not set in the configs.xml file?

**Comment by alandtse** [comment]
> 4. In the configs.xml file, could you please make explicit what is the default value in the code, ie if the value is not set in the configs.xml file?

I thought I did. https://github.com/DaymareOn/hdtSMP64/pull/34/files#diff-0beda8959fd61c710a0252b97ab28b26b4d83e5b207f7a93dc2db08df456d922R200

**Comment by DaymareOn** [comment]
5. In hdtSkinnedMeshWorld.cpp line 154, there is an equality test between 2 floats, which is faulty. The existing code generally uses the inline functions btFuzzyZero or btEqual.

**Comment by DaymareOn** [comment]
> > 4. In the configs.xml file, could you please make explicit what is the default value in the code, ie if the value is not set in the configs.xml file?
> 
> I thought I did. https://github.com/DaymareOn/hdtSMP64/pull/34/files#diff-0beda8959fd61c710a0252b97ab28b26b4d83e5b207f7a93dc2db08df456d922R200

Sorry, I wasn't clear. Currently for lots of settings in FSMP, the default value in the code is different from the default value in the configs.xml file.
Mentioning in configs.xml the default value from the code is interesting because it makes explicit what value is applied when the setting isn't set in configs.xml especially if we change later the recommended values in configs.xml.
Mentioning the default value in the configs.xml file is interesting for users to known what is the recommended value.
I understand that currently these values might be the same for these settings, but I'd like this fact to be explicit.

**Comment by alandtse** [comment]
> Sorry, I wasn't clear. Currently for lots of settings in FSMP, the default value in the code is different from the default value in the configs.xml file.

That is the problem. All my defaults I mention should match what happens without any setting for any of the code I submitted. Anything that doesn't is a bug someone can fix.

**Comment by alandtse** [comment]
It'd be easier if you just responded with comments in line so we can use the natural Github resolve features.
1. That was borrowed from Shizof. We can optimize at a later stage once we're sure we want the feature.
2. This is where we've had disagreements in the past. Microoptimizations aren't useful unless it's part of the critical path. If we're hunting for performance, it has to be targeted. As a note I've enabled MT in my own build and that resulted in a noticeable improvement on physics processing. On my system, I'm seeing a factor of 2-4 improvement on time spent per activeSkeletons. I've never seen the prior microoptimizations help to that level.
3. Interesting feature request for a later date. Probably, but again I'm getting us to a MVP and borrowing existing things from Shizof.
4. All my config values have this property. To the extent you see any that don't from me, I can fix it. To the extent it's from someone else, then that's a bug perhaps we can convince someone to fix as a first submission.
5. Fixed.

**Comment by DaymareOn** [comment]
> It'd be easier if you just responded with comments in line so we can use the natural Github resolve features.

Oh yes, sorry.

> 1. That was borrowed from Shizof. We can optimize at a later stage once we're sure we want the feature.

Ok for me.

> 2. This is where we've had disagreements in the past. Microoptimizations aren't useful unless it's part of the critical path. If we're hunting for performance, it has to be targeted. As a note I've enabled MT in my own build and that resulted in a noticeable improvement on physics processing. On my system, I'm seeing a factor of 2-4 improvement on time spent per activeSkeletons. I've never seen the prior microoptimizations help to that level.

I agree.
Hmm, how did you enable MT in your build? I always build the dlls I provide with /MT, for SE, AE, VR.

> 3. Interesting feature request for a later date. Probably, but again I'm getting us to a MVP and borrowing existing things from Shizof.

Ok for me.

> 4. All my config values have this property. To the extent you see any that don't from me, I can fix it. To the extent it's from someone else, then that's a bug perhaps we can convince someone to fix as a first submission.

Ok, The settings with different default values in the configs.xml file and in the source code are:
- unclampedResetAngle: 130 vs 120,
- autoAdjustMaxSkeleton: false vs true,
- enableCuda (well, it's ignored when not read by a CUDA build, so this allows to avoid shipping/maintaining 2 different configs.xml files): true vs false,
- numIterations: 16 vs 10,
- groupIterations: 16 vs 2,
- groupEnableMLCP: false vs true.

I can do the changes, excepted if you have somebody to propose?

> 5. Fixed.

**Comment by DaymareOn** [comment]
"We can optimize at a later stage once we're sure we want the feature."

Well, I guess we want it, except if we have problems.
I see 2 possible problems: 
- it doesn't work => it works on your setup, so we would need to release it to find the corner cases where it doesn't work.
- the performance is bad => and yet some would like to have it, so the best we could do would be to make it enablable.

Conclusion: depending on when you'd like to release it to masses, and if an enabling system is implemented, we need or not to go through a branch on my repo, am I right?

**Comment by alandtse** [comment]
> Hmm, how did you enable MT in your build? I always build the dlls I provide with /MT, for SE, AE, VR.
> 
> >

Bullet has multithreaded variants that we weren't using apparently. #35 

> Ok, The settings with different default values in the configs.xml file and in the source code are:
> 
> * unclampedResetAngle: 130 vs 120,
> * autoAdjustMaxSkeleton: false vs true,
> * enableCuda (well, it's ignored when not read by a CUDA build, so this allows to avoid shipping/maintaining 2 different configs.xml files): true vs false,
> * numIterations: 16 vs 10,
> * groupIterations: 16 vs 2,
> * groupEnableMLCP: false vs true.
> 
> I can do the changes, excepted if you have somebody to propose?

I was thinking just make it an open issue with a tag that's it's good for first contributors. Or you could do it.

> Well, I guess we want it, except if we have problems. I see 2 possible problems:
> 
> * it doesn't work => it works on your setup, so we would need to release it to find the corner cases where it doesn't work.
> * the performance is bad => and yet some would like to have it, so the best we could do would be to make it enablable.
> 
> Conclusion: depending on when you'd like to release it to masses, and if an enabling system is implemented, we need or not to go through a branch on my repo, am I right?

The feature is controlled by the enable switch. https://github.com/DaymareOn/hdtSMP64/blob/369ad4b0d67c2c07c16811ac8927544e573976ee/hdtSMP64/config/configs.xml#L205

I'm letting VR users do some testing on my build, but I defer to you since you have the harder job of doing multiple versions. My PR shouldn't break your build. The only thing that isn't implemented though is AE addresses. But apparently you have someone who knows how to grab them who can help.

**Comment by alandtse** [comment]
I'm going to close the perf branch since it's just integrated into here now.

**Review by DaymareOn — APPROVED** [review]

**Pull request merged**
